### ISSUE TITLE
Find other datasets for result comparison

### ISSUE THREAD

**Issue by SeanLF** [SeanLF/CSI4900#6]
find other datasets that we can train/test on to compare our results

**Comment by markkasun** [comment]
Importing 4 University dataset into db and running learn algorithms on them.

**Comment by rsafi082** [comment]
Found some other datasets and some of their results. Below are some links that may be of use:
* [PDF listing data sets used](http://www.jmlr.org/proceedings/papers/v16/supplemental/Datasets_AL_challenge.pdf)
* [Results from the data sets](http://jmlr.csail.mit.edu/proceedings/papers/v16/guyon11a/guyon11a.pdf)
* [Data sets](https://github.com/iitml/AL/tree/master/empirical_study_datasets)

Another interesting link that _may_ be useful: [here](https://github.com/biolab/orange3)
